name: base
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - cufflinks-py=0.17.3=py_0
  - pandas
  - path=13.1.0=py37_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py37_0
  - pathtools=0.1.2=py_1
  - plotly=4.8.1=py_0
  - plotly-orca=1.3.1=1
  - scikit-image
  - scikit-learn
  - scipy
  - xlsxwriter=1.2.7=py_0
  
