dependencies:
  - cufflinks-py=0.17.3=py_0
  - openpyxl
  - pandas
  - path=13.1.0
  - path.py=12.4.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - plotly=4.8.1
  - plotly-orca=1.3.1
  - scikit-image
  - scikit-learn
  - scipy
  - xlsxwriter=1.2.7
  - openpyxl
  
